### PR TITLE
Squeezing as much utility out as possible

### PR DESCRIPTION
**Pull request by WanderLanz**
I finally had some time for OSS, so a good a time as ever to help out here. I'm definitely going to teeter on the edge of UB here, but I'm not going completely haywire like `lender` so hopefully no obvious UB at least....

I'm mostly opening the draft so that someone can tell me when I'm being an idiot before I go making a 200 line module we end up not using (I ended up not using TrustedLen)

### CODE REVIEW

**Comment by Crazytieguy** [comment]
Hi, thanks for all this work!

I generally really like the things you've done, but I'm not comfotrable with the amount of new design choices in this one PR. would you feel comfortable splitting it into several PRs, so it's easier to discuss each change separately? For instance there could be a PR just for the inline annotations, a PR for just the alloc feature, a PR for the try_* methods, a PR for the TrustedLen stuff etc.

Things that I would need to understand thoroughly and have a discussions on the tradeoffs of before merging would be all of the unsafe stuff, the addition of the `nightly` feature, and the addition of `no_std`. Unfortunately I might not have enough time in the next ~week or two to do those, but I'd like to merge the other stuff. If @ratmice wants to review them and have the discussion I trust his judgement.

**Comment by ratmice** [comment]
"teetering on the edge of UB" sounds scary to me, and I'm also going to be fairly busy but agree that if things were split up it'd be helpful.

**Comment by WanderLanz** [comment]
Definitely not ready for a in-depth review, I'm still testing what's working and ensuring safety in design, so don't feel any pressure or anything.

**Comment by WanderLanz** [comment]
I really overestimated the amount of time I had available 😅. I will probably go ahead and break down what I'm thinking to let others work on it or open other prs without having to understand my inconsistency. 

On that topic, I'm no expert so please correct me where I'm wrong, misinformed, or suggesting something unnecessary, there's absolutely no judgement here ❤️. Also, sorry for the info dump, could probably make a proper suggested "roadmap" out of this but I'm too lazy and some stuff is still undecided.

#### General/Non-"Feature" Changes

- [ ] `inline` attributes <details><summary>ℹ️</summary>Rustc can only aggressively inline within a single translation unit (crate), after which it mostly the responsibility of the linker. This is why most library crates error on the side of `#[inline]`.</details>
- [ ] `must_use` attributes <details><summary>ℹ️</summary>Iterators of any type must be consumed in order to perform work. This attribute helps warn users of potential errors before they have to debug. Recent `must_use` strengthening make this attribute even more helpful.</details>
- [ ] `no_std` <details><summary>ℹ️</summary>Iterators are powerful tools that should be available even within `no_std` code. Users can still use `std` even when this crate has `#![no_std]`. We may use a `alloc` or even `std` feature to gate `alloc`-utilizing utilities such as buffered windows. This may make tests and examples more contrived to work with, but that shouldn't be too much of an issue. This may also potentially help with possibly introducing this to std, even though that will more likely be covered by an `effects` change of some sort.</details>
- [ ] `Clone`, `Debug` derives <details><summary>ℹ️</summary>Even though lending iterators are commonly expensive to clone, it is reasonable to expect `Clone` or `Debug` as parity with regular Iterators. This isn't a necessary change, but rather one I think would help ease potential mental and boilerplate burden for users. </details>
- [ ] ```impl<I: LendingIterator + ?Sized> LendingIterator for &mut I``` <details><summary>ℹ️</summary>Although it will definitely cause headaches with other generic trait impls without specialization, it is incredibly ergonomic for normal iterators and likewise for lending iterators.</details>

#### Features

- [ ] "HasNext" trait `fn ...(&mut self) -> bool` <details><summary>ℹ️</summary>Iterator/core::iter had some discussion about including a similar trait, but I believe it is an order of magnitude more useful for lending iterators and is the backbone of some of the implementations henceforth that would otherwise rely on potential UB or clumsiness (e.g. `pin!(iter.peekable()).as_mut().peek()`).</details>
- [ ] `LendingIterator::last` <details><summary>ℹ️</summary>We can just loosely rely on behavior of `size_hint` in order to implement last. This *IS* different behavior than Iterator::last, but still provides some ergonomics I think are worth it.</details>
- [ ] `LendingIterator::try_for_each`, `LendingIterator::try_fold` <details><summary>ℹ️</summary>Utilizes own implementation of `try_trait_v2` at least until that is stabilized. Compiler inference will fail, so we may possibly still want to include a `closure_lifetime_binder` feature replacement. </details>
- [ ] `LendingIterator::intersperse` <details><summary>ℹ️</summary>Utilizing the "HasNext" trait, we could implement intersperse with the same behavior as Iterator::intersperse, without directly relying on `peekable`.</details>
- [ ] `LendingIterator::peekable` <details><summary>ℹ️</summary>I don't _believe_ there's many potential UBs beyond having a self-referential struct, which would require `pin!` in order to peek. As a rule, implementation should keep in mind that having a peeked item is the same as having `&mut inner_iter` still alive and shouldn't even operate on `& inner_iter` while a peek is still alive.</details>
- [ ] Other methods that have different behavior but same utility. e.g. `next_chunk`, `array_chunks` via iterators rather than arrays <details><summary>ℹ️</summary>Not required, but likewise nice to have.</details>
- [ ] Other "easy" missing methods, e.g. `eq` or `is_sorted` <details><summary>ℹ️</summary>Either by requiring `'static` for HRTBs or `ToOwned`, there's not much ways to get around stricter requirements here without HRTB improvements or specialization.</details>
- [ ] Other "hard" missing methods that are too spicy for the current ownership model, e.g. `find` and `find_map` <details><summary>ℹ️</summary>This class of methods usually just involve Polonius returns.</details>
- [ ] Other utility traits, e.g. General `IntoLendingIterator`, `ExactSizeLendingIterator`, `FusedLendingIterator`, `DoubleEndedLendingIterator`, `Sum` & `Product` as mathematical concepts rather than strict arithmetic, etc. <details><summary>ℹ️</summary>These are probably less commonly utilized for lending iterators than the equivalent core::iter traits, but should still eventually be considered.</details>

**Comment by Crazytieguy** [comment]
Hey :)
the "non-feature" changes all seem good to me, although I'm not sure `impl<I: LendingIterator + ?Sized> LendingIterator for &mut I` is necessary, don't we just get it out of the box?

For the features - I'd really like to have a separate issue for each of them so we can discuss them in detail. I expect to have some time to work on this crate around late March - April

**Comment by WanderLanz** [comment]
👍 I'll go ahead and open another issue for that then.

I'll probably just open essential feature issues that don't invoke 'static or can be easily replaced in a for loop.

**Pull request closed without merging**
